<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fundamentos JavaScript</title>
</head>
<body> 
 <h1> Fundamoentos JavaScript</h1>
</body>
<script>

/* **********     Curso JavaScript: 16. Manejo de Errores - #jonmircha     ********** */
  
//En el try se agrega el codigo a evaluar, catch captura el error
//El finally siempre se ejecuta
try {
       console.log("En el Try se agrega el código a evaluar");
       noExiste;
       console.log("Segundo mensaje en el try");
     } catch (error) {
       console.log("Catch, captura cualquier error surgido o lanzado en el try");
       console.log(error);
     } finally {
       console.log("El bloque finally se ejecutará siempre al final de unbloque try-catch");
     }
     try {
       let numero = "y";
       if (isNaN(numero)) {
         throw new Error("El caractér introducido no es un Número");
       }
       console.log(numero * numero);
     } catch (error) {
       console.log(`Se produjo el siguiente error: ${error}`);
     } 

</script>
</html>